DevB33/metro-client

src/app/_components/sidebar/finder/finder-card.tsx, src/app/_components/sidebar/finder/page-item.tsx
- 페이지 추가 기능 구현
---
- mock데이터를 로컬 스토리지에 저장
- 상태를 통해 즉시 반영
---
---
https://github.com/user-attachments/assets/b1887ff4-5d84-4cd2-a021-b405d7b74603
---
**설명**: UI 변경 사항이 포함된 경우, 변경된 화면을 시각적으로 보여주기 위해 스크린샷이나 동영상을
첨부하면 도움이 됩니다. 리뷰어는 화면 변경 사항을 바로 확인할 수 있어 코드 리뷰가 더 효과적입니다.
---
=> Feat : 페이지 추가 기능 구현

package-lock.json, package.json, panda.config.ts, src/app/(main)/note/[id]/_components/note-header/hover-menu.tsx, src/app/(main)/note/[id]/_components/note-header/icon-selector.tsx, src/app/(main)/note/[id]/_components/note-header/note-header.tsx, src/app/(main)/note/[id]/_components/note-header/tag-box.tsx, src/app/(main)/note/[id]/_components/note-header/tag.tsx, src/app/(main)/note/[id]/_components/note-header/title.tsx, src/constants/line-color.ts, src/icons/image-icon.tsx, src/icons/smile-icon.tsx, src/icons/tag-icon.tsx, src/types/tag-type.ts
- 아이콘 셀렉터 및 태그 구현
---
- EmojiPicker 라이브러리를 이용해 이모지 셀렉터 구현
- 이모지 선택 및 삭제 기능 구현
- 제목 input 으로 변경
- 태그 구현
-  엔터키 입력 시 input이 태그가 되도록 구현
- 랜덤 색상이 입혀지도록 구현
- 수정 상태에서 x 버튼을 누르면 삭제되도록 구현
- 중복된 태그 입력하지 못하도록 구현
- 길이가 길어지면 다음 줄로 넘어가도록 구현
---
https://github.com/user-attachments/assets/51de7d6e-c74e-4c12-8010-e9e6771f3d7a
> iconSelector 기능
https://github.com/user-attachments/assets/0e042400-6894-48fb-819b-c8cf29af0482
> Tag 기능
---
=> Feat: 아이콘 셀렉터 및 태그 구현

src/app/(main)/note/[id]/_components/note-content/block.tsx
- 줄 바꿈 된 상태에서도 잘 동작하도록 블록 병합 로직 변경
---
- block 컴포넌트의 merge 함수 수정
---
---
=> feat: 줄 바꿈 된 상태에서도 잘 동작하도록 블록 병합 로직 변경

src/app/(main)/note/[id]/_components/note-content/note-content.tsx
- 블록 호버 에러 해결
---
- 블록 호버시 빠르게 움직이면 호버 상태가 아니어도 호버로 인식되는 에러를 해결하였습니다.
- 입력 시작시 호버가 아닌 상태로 바꾸고, 마우스를 움직이면 다시 호버 상태로 돌리도록 하였습니다.
---
---
https://github.com/user-attachments/assets/d7c9d3e1-9fc3-424b-9ae2-6a1ada91810a
---
**설명**: UI 변경 사항이 포함된 경우, 변경된 화면을 시각적으로 보여주기 위해 스크린샷이나 동영상을
첨부하면 도움이 됩니다. 리뷰어는 화면 변경 사항을 바로 확인할 수 있어 코드 리뷰가 더 효과적입니다.
---
=> feat: 블록 호버 에러 해결

src/app/(main)/_components/sidebar/sidebar.tsx, src/app/(main)/note/[id]/_components/header.tsx, src/app/(main)/note/[id]/_components/line-info/line-info.tsx, src/app/(main)/note/[id]/_components/note-content/block-button.tsx, src/app/(main)/note/[id]/_components/note-content/note-content.tsx, src/app/(main)/note/[id]/_components/note-header/cover-dropdown/dropdown.tsx, src/app/(main)/note/[id]/_components/note-header/note-cover.tsx, src/app/(main)/note/[id]/_components/note-header/tag.tsx, src/app/(main)/note/[id]/_components/note-header/title.tsx, src/app/(main)/note/[id]/page.tsx
-  사이드바에 블록 호버가 가려지는 현상 해결
---
-  사이드바에 블록 호버가 가려지는 현상 해결
- cover 변경 모달창 위치가 페이지 크기를 따르지 않는 현상 해결
---
---
https://github.com/user-attachments/assets/35dff8fb-583b-4786-9c2e-966aa3466e9b
---
**설명**: UI 변경 사항이 포함된 경우, 변경된 화면을 시각적으로 보여주기 위해 스크린샷이나 동영상을
첨부하면 도움이 됩니다. 리뷰어는 화면 변경 사항을 바로 확인할 수 있어 코드 리뷰가 더 효과적입니다.
---
=> feat: 사이드바에 블록 호버가 가려지는 현상 해결

src/app/(main)/note/[id]/_components/note-content/note-content.tsx
- 블록 focus 문제 해결
---
- useState를 이용한 블록 버튼의 나타나고 사라지는 로직을 useRef로 변경했습니다.
---
---
- useState로 인한 재렌더링으로 인해 focus가 블록의 맨 윗줄로 이동하는 현상 발생
- 이를 방지하기 위해 useRef를 이용한 DOM 조작으로 코드 수정
---
**설명**: 이 PR과 관련된 추가적인 정보를 작성하여 리뷰어가 작업의 맥락을 이해하고, 리뷰에 필요한
내용을 쉽게 참고할 수 있도록 합니다. 이를 통해 PR의 내용을 명확히 전달할 수 있습니다.
---
https://github.com/user-attachments/assets/ca8b338c-b48b-4b22-ae15-7bb38de2d207
---
**설명**: UI 변경 사항이 포함된 경우, 변경된 화면을 시각적으로 보여주기 위해 스크린샷이나 동영상을
첨부하면 도움이 됩니다. 리뷰어는 화면 변경 사항을 바로 확인할 수 있어 코드 리뷰가 더 효과적입니다.
---
=> feat: 블록 focus 문제 해결

src/app/(main)/_components/sidebar/finder/edit-title-modal.tsx, src/app/(main)/_components/sidebar/finder/page-item.tsx, src/app/(main)/note/[id]/_components/note-header/note-header.tsx, src/app/(main)/note/[id]/_components/note-header/tag.tsx, src/app/(main)/note/[id]/_components/note-header/title.tsx, src/app/(main)/note/[id]/page.tsx, src/components/dropdown/dropdown-menu.tsx, src/types/page-type.ts
- 사이드바 제목 수정 모달 구현
---
- 제목 수정 모달 구현
- 드랍다운 클릭 시 페이지 이동이 되지 않도록 방지 (삭제 시 페이지 이동이 일어나면 없는 페이지로 이동되어 오류)
- noteHeaderData가 고유 key값을 가지도록 하여 수정 시 다른 data를 수정하는 것을 방지
---
https://github.com/user-attachments/assets/b02d76b9-1357-472e-9155-1f9265b1e168
---
=> Feat : side bar edit modal

src/app/(main)/note/[id]/_components/note-content/block/_handler/handleKeyDown.ts, src/app/(main)/note/[id]/_components/note-content/block/_handler/handleMouseDown.ts, src/app/(main)/note/[id]/_components/note-content/block/_handler/handleMouseLeave.ts, src/app/(main)/note/[id]/_components/note-content/block/_handler/handleMouseMove.ts, src/app/(main)/note/[id]/_components/note-content/block/block.tsx, src/app/(main)/note/[id]/_components/note-content/block/slash-menu.tsx
- keyDown 이벤트 후 focus 관리
---
- 블록 클릭 시 클릭 위치에 focus 주는 로직 수정
- 줄 나누기/합치기 시 focus 유지
- 블록 나누기/합치기 시 focus 유지
- 방향키로 블록 간 focus 이동
---
---
- 블록 합친 직후에 그 위치에서 글자 지울 때 에러 해결
- 블록 합친 직후에 그 위치에서 줄 나눌 때 에러 해결
- 빈줄에서 줄 합칠 때 focus 이상했던 이슈 해결
- 빈 줄로 블록 합치기 할 때 에러 해결
- 빈 블럭에서 위아래 블록으로 커서 이동 시 에러 + focus 이동 안되던 이슈 해결
---
**설명**: 이 PR과 관련된 추가적인 정보를 작성하여 리뷰어가 작업의 맥락을 이해하고, 리뷰에 필요한 내용을 쉽게 참고할 수
있도록 합니다. 이를 통해 PR의 내용을 명확히 전달할 수 있습니다.
---
https://github.com/user-attachments/assets/894f7886-8945-4932-bcd2-9528304ec458
---
---
=> feat: 포커스 관리

src/app/(main)/note/[id]/_components/note-content/block/_handler/handleKeyDown.ts, src/app/(main)/note/[id]/_components/note-content/block/_handler/handleMouseDown.ts, src/app/(main)/note/[id]/_components/note-content/block/block-tag.tsx, src/app/(main)/note/[id]/_components/note-content/block/selection-menu.tsx, src/app/(main)/note/[id]/_components/note-content/block/slash-menu.tsx, src/app/(main)/note/[id]/_components/note-content/note-content.tsx
- selection menu 클릭시 외부 클릭으로 인한 selection 위치 초기화가 먼저 진행되어 selection 변경이 이루어지지 않는 문제 해결
=> feat: selection 위치 초기화 문제 및 기타오류 해결

package-lock.json, package.json, src/app/(main)/_components/chart/LinkControls.tsx, src/app/(main)/_components/chart/chart.tsx, src/app/(main)/_components/chart/getLinkComponent.ts, src/app/(main)/_components/chart/useForceUpdate.ts, src/app/(main)/_components/sidebar/side-menu/home-button.tsx, src/app/(main)/note/[id]/_components/note-content/note-content.tsx, src/app/(main)/page.tsx, src/constants/line-color.ts, src/icons/reset-icon.tsx
- homepage에 Chart 구현
---
- homePage 내의 chart 구현
- random color와 디자인을 통해 metro같은 차트로 수정
- note API 와 연동하여 페이지 이동이 가능하도록 구현
- zoom이 가능하도록 구현
---
https://github.com/user-attachments/assets/47aa9ee6-f7b8-4019-a9cb-8554c9856b8a
---
=> Feat : homePage chart 구현

src/app/(main)/_components/sidebar/finder/page-item.tsx, src/app/(main)/note/[id]/_components/header.tsx
- noteHeader 뒤로가기 및 삭제 구현
---
- 뒤로가기 버튼 구현
- 헤더에서 페이지 삭제하기 버튼 구현
- 열려있는 페이지에서 자신의 페이지 삭제 시 home으로 redirect 하도록 구현
---
https://github.com/user-attachments/assets/35cdf978-1e88-4248-abc6-3ae9e9dcdf13
https://github.com/user-attachments/assets/3a1b0db4-6df6-4e25-b8fd-6322385e172e
---
=> Feat : noteHeader 뒤로가기 및 삭제 구현

src/app/(main)/note/[id]/_components/note-content/block/_handler/handleKeyDown.ts, src/app/(main)/note/[id]/_components/note-content/block/_handler/handleMouseUp.ts, src/app/(main)/note/[id]/_components/note-content/block/block.tsx, src/app/(main)/note/[id]/_components/note-content/block/selectionDelete.ts, src/app/(main)/note/[id]/_components/note-content/block/selectionWrite.ts, src/app/(main)/note/[id]/_components/note-content/note-content.tsx
- selection 지우기 및 글씨 쓰기 구현
---
- selection이 설정 된 후 delete 입력시 선택된 영역을 제거
- selection이 설정 된 후 일반적인 키보드 입력시 선택된 영역을 제거하고 입력한 키로 노드를 생성해 selection start 위치에 삽입
---
---
https://github.com/user-attachments/assets/be02239b-c794-4ef0-bf18-33be7a7d3345
---
---
=> Feat : selection 지우기 및 글씨 쓰기

src/app/(main)/_components/chart/chart.tsx, src/app/(main)/_components/chart/responsiveWrapper.tsx, src/app/(main)/_components/sidebar/finder/edit-title-modal.tsx, src/app/(main)/_components/sidebar/finder/finder-card.tsx, src/app/(main)/_components/sidebar/finder/page-item.tsx, src/app/(main)/_components/sidebar/profile/profile-card.tsx, src/app/(main)/_components/sidebar/side-menu/side-menu-card.tsx, src/app/(main)/layout.tsx, src/app/(main)/note/[id]/_components/note-content/block/_handler/handleKeyDown.ts, src/app/(main)/note/[id]/_components/note-content/note-content.tsx, src/app/(main)/note/[id]/_components/note-header/note-header.tsx, src/app/(main)/note/[id]/_components/note-header/tag.tsx, src/app/(main)/note/[id]/_components/note-header/title.tsx, src/app/(main)/note/[id]/page.tsx, src/app/(main)/page.tsx
- 여러 이슈 해결 및 사이드바 관련 구조 개선
---
- 외부 드래그 배경 전체칠해지던 이슈 해결
- 외부 드래그 시 offset이 잘 적용되도록 구현
- 잘못된 swr 제거
- noteHeaderData -> noteMetaData 로 명칭 변경
- sidebar에서 해상도에 따라 작아지는 이슈 해결 및 pageList가 길어지면 스크롤이 생기도록 구현
- chart 컴포넌트 명 변경 및 크기를 반응형으로 구현
- shift + 방향키를 사용하지 못하도록 막음
- 사이드 바 우클릭 기능 구현
- dropdown이 portal로 바뀌며 여러개 열리던 이슈 해결
---
=> Feat : 여러 이슈 해결 및 사이드바 관련 구조 개선

src/app/(main)/note/[id]/_components/note-content/block/_handler/handleMouseUp.ts, src/app/(main)/note/[id]/_components/note-content/note-content.tsx
- selection 위치 정확도 개선
---
- mouse move에만 있던 selection End Position 설정을 mouse up 에 추가
---
---
https://github.com/user-attachments/assets/35fdce74-c734-4347-b954-24fb5d249549
---
---
=> Feat: selection 위치 정확도 개선

src/app/(main)/@modal/(.)search-modal/_component/searchResult.tsx, src/app/(main)/_components/chart/chart.tsx, src/app/(main)/_components/sidebar/finder/edit-title-modal.tsx, src/app/(main)/_components/sidebar/finder/finder-card.tsx, src/app/(main)/_components/sidebar/finder/page-item.tsx, src/app/(main)/layout.tsx, src/app/(main)/note/[id]/_components/header.tsx, src/app/(main)/note/[id]/_components/note-content/block-button.tsx, src/app/(main)/note/[id]/_components/note-content/block/_handler/handleKeyDown.ts, src/app/(main)/note/[id]/_components/note-content/block/_handler/handleMouseDown.ts, src/app/(main)/note/[id]/_components/note-content/block/_handler/handleMouseLeave.ts, src/app/(main)/note/[id]/_components/note-content/block/_handler/handleMouseMove.ts, src/app/(main)/note/[id]/_components/note-content/block/_handler/handleMouseUp.ts, src/app/(main)/note/[id]/_components/note-content/block/block.tsx, src/app/(main)/note/[id]/_components/note-content/block/selection-menu.tsx, src/app/(main)/note/[id]/_components/note-content/block/selectionChange.ts, src/app/(main)/note/[id]/_components/note-content/block/selectionDelete.ts, src/app/(main)/note/[id]/_components/note-content/block/selectionEnter.ts, src/app/(main)/note/[id]/_components/note-content/block/selectionWrite.ts, src/app/(main)/note/[id]/_components/note-content/block/slash-menu.tsx, src/app/(main)/note/[id]/_components/note-content/note-content.tsx, src/app/(main)/note/[id]/_components/note-header/note-header.tsx, src/app/(main)/note/[id]/_components/note-header/tag.tsx, src/app/(main)/note/[id]/_components/note-header/title.tsx, src/constants/button-offset.ts, src/constants/placeholder.ts, src/types/menu-type.ts, src/types/selection-position.ts
- noteContent 관련 리팩토링 및 간단한 로직 수정
---
- 이해하기 쉽도록 주석 추가
- page -> note 로 명칭 변경
- selection 관련 변수 하나로 묶어 관리
- menu 관련 변수 하나로 묶어 관리
- 버튼 위치 상수 분리
- slashMenu 여러개 띄워지던 오류 수정
- 현재 페이지  삭제 시 home으로 redirect 수정
- span이 제대로 칠해지지 않던 문제 수정
---
=> Refactor : noteContent 관련 리팩토링 및 간단한 로직 수정

src/apis/block.ts, src/app/(main)/layout.tsx, src/app/(main)/note/[id]/_components/note-content/block-button.tsx, src/app/(main)/note/[id]/_components/note-content/block/block-html-tag.tsx, src/app/(main)/note/[id]/_components/note-content/block/block.tsx, src/app/(main)/note/[id]/_components/note-content/block/handler/handleInput.ts, src/app/(main)/note/[id]/_components/note-content/block/handler/handleKeyDown.ts, src/app/(main)/note/[id]/_components/note-content/block/handler/handleMouseDown.ts, src/app/(main)/note/[id]/_components/note-content/ghost-block/ghost-block-html-tag.tsx, src/app/(main)/note/[id]/_components/note-content/ghost-block/ghost-block.tsx, src/app/(main)/note/[id]/_components/note-content/note-content.tsx, src/app/(main)/note/[id]/page.tsx, src/types/block-type.ts
- 블록 api 연동
---
- 블록 생성 api 연동
- 블록 삭제 api 연동
- 블록 수정 api 연동
- 블록 순서 변경 api 연동
- 블록 나누기 / 합치기 api에 맞게 수정
- 줄 나누기 / 합치기 api에 맞게 수정
- foucs 로직 api에 맞게 수정
---
---
=> feat: 블록 api 연동

src/app/(main)/note/[id]/_components/note-content/block-button.tsx, src/app/(main)/note/[id]/_components/note-content/block/block-html-tag.tsx, src/app/(main)/note/[id]/_components/note-content/block/block.tsx, src/app/(main)/note/[id]/_components/note-content/block/handler/handleInput.ts, src/app/(main)/note/[id]/_components/note-content/block/handler/handleKeyDown.ts, src/app/(main)/note/[id]/_components/note-content/ghost-block/ghost-block-html-tag.tsx, src/app/(main)/note/[id]/_components/note-content/note-content.tsx, src/app/(main)/note/[id]/_components/note-content/slash-menu/slash-menu.tsx, src/types/block-type.ts
- 블록 순서 변경, 타입 변경, 블록 버튼을 통한 블록 생성/삭제 API 연동
---
- 드래그 엔 드롭을 통한 블록 순서 변경 기능에 블록 순서 변경 API 연동
- 마크다운 명령어 입력을 통한 블록 타입 변경 가능에 블록 타입 변경 API 연동
- 슬래시 메뉴를 통한 블록 타입변경 가능에 블록 타입 변경 API 연동
- 블록 버튼을 통한 블록 생성 및 삭제 기능에 블록 생성, 블록 삭제, 블록 순서 변경 API 연동
---
---
https://github.com/user-attachments/assets/a15c7f11-5db4-491e-aaa2-b717f729140d
---
---
=> feat: 블록 순서 변경, 타입 변경, 블록 버튼을 통한 블록 생성/삭제 API 연동

src/apis/note.ts, src/app/(main)/note/[id]/_components/header.tsx, src/app/(main)/note/[id]/_components/note-content/block/block-html-tag.tsx, src/app/(main)/note/[id]/_components/note-content/block/block.tsx, src/app/(main)/note/[id]/_components/note-content/block/handler/handleKeyDown.ts, src/app/(main)/note/[id]/_components/note-content/note-content.tsx, src/app/(main)/note/[id]/_components/note-content/selection-menu/changeSelectionStyle.ts, src/app/(main)/note/[id]/_components/note-content/selection-menu/editSelectionContent.ts, src/app/(main)/note/[id]/_components/note-content/selection-menu/selection-menu.tsx, src/app/(main)/note/[id]/_components/note-content/slash-menu/slash-menu.tsx
- api 관련 작업 수정 및 qa 해결
---
- noteList에서 note 생성 시 api url 수정
- header의 뒤로가기 버튼을 상위페이지가 아닌 router의 back 형식으로 변경
- 사용하지 않는 mock BlockList 삭제 및 api를 사용하도록 전체 코드 수정
- h1, h2, h3 로 전환 시 placeholder에 여백이 컸던 문제 해결
- changeBlock 시 focus가 제대로 되지 않던 문제 해결
---
- 임시 blockList와 setBlockList를 사용하지 않도록 변경하고 api를 사용하도록 했습니다.
- blockList[index].type 을 판단하는 조건문에서, type이 이전 값을 참조하고 있어 제대로 focus가 되지 않던 문제를 해결했습니다.
---
=> Fix : api 관련 작업 수정 및 qa 해결

src/apis/block.ts, src/apis/note.ts, src/app/(main)/@modal/(.)search-modal/_component/searchResult.tsx, src/app/(main)/_components/sidebar/finder/edit-title-modal.tsx, src/app/(main)/_components/sidebar/finder/page-item.tsx, src/app/(main)/note/[id]/_components/note-content/block/block-html-tag.tsx, src/app/(main)/note/[id]/_components/note-content/block/block.tsx, src/app/(main)/note/[id]/_components/note-content/block/handler/handleKeyDown.ts, src/app/(main)/note/[id]/_components/note-content/note-content.tsx, src/app/(main)/note/[id]/_components/note-content/slash-menu/slash-menu.tsx, src/icons/menu-page-icon.tsx, src/types/block-type.ts
- 페이지 블록 생성 구현
---
- 마지막에 페이지 생성시 다음에 빈 블록 생성
- block데이터 가져오면 거기서 note블록 있으면 상세 데이터 가져오기
---
---
> UI 변경 사항이 있는 경우 스크린샷이나 동영상을 첨부해주세요. 예: 변경된 로그인 페이지 화면 캡처
---
---
=> Feat : 페이지 블록 생성 구현

package-lock.json, src/apis/note.ts, src/app/(main)/_components/sidebar/finder/finder-card.tsx, src/app/(main)/_components/sidebar/finder/note-item.tsx, src/app/(main)/note/[id]/_components/note-content/block/block-html-tag.tsx, src/app/(main)/note/[id]/_components/note-content/block/block.tsx, src/app/(main)/note/[id]/_components/note-content/slash-menu/slash-menu.tsx, src/types/note-type.ts
- 사이드 바 노트 순서 이동
---
- 사이드 바에서 페이지 드래그앤 드롭
- 페이지 드롭시 해당 위치로 순서 변경
- 페이지 상세에 순서 반영
---
---
https://github.com/user-attachments/assets/c3a74fe2-a5d3-45f1-a4e6-c7c46fc448d8
---
---
=> feat: 사이드 바 노트 순서 이동

src/app/(main)/note/[id]/_components/note-content/block-button.tsx, src/app/(main)/note/[id]/_components/note-content/block/block.tsx, src/app/(main)/note/[id]/_components/note-content/block/handler/handleKeyDown.ts, src/app/(main)/note/[id]/_components/note-content/note-content.tsx, src/app/(main)/note/[id]/_components/note-content/slash-menu/slash-menu.tsx
- 페이지 블록 에러 해결
---
- 맨 마지막이 페이지면 빈블록 생성
- 페이지 삭제 시 사이드바 반영
---
---
=> fix: 페이지 블록 에러

src/app/(main)/note/[id]/_components/note-content/block/block-html-tag.tsx, src/app/(main)/note/[id]/_components/note-content/block/handler/handleKeyDown.ts, src/app/(main)/note/[id]/_components/note-content/block/handler/handleMouseUp.ts, src/app/(main)/note/[id]/_components/note-content/note-content.tsx
- page block focus issue 및 빈 블록 생성 구현
---
- 방향키를 이용한 focus 로직을 수정하여 중간에 페이지 블록이 있더라도 잘 작동하도록 구현하였습니다.
- 비정상적으로 작동하던 방향키 로직을 수정하였습니다.
- 페이지 블록이 제일 아래에 있을 때, 하단 빈 공간을 클릭하면 빈 블록이 생성되도록 구현하였습니다.
---
- 페이지 블록이 여러개 있을 경우에도 잘 작동하도록 구현하였습니다.
- quote의 경우 통일성을 위해 기본 style에서 margin을 제거하였고, 후처리를 통해 focus가 잘 이동하도록 하였습니다.
---
https://github.com/user-attachments/assets/9e081175-5cd1-465c-a0c5-089f81ada41d
https://github.com/user-attachments/assets/6c48d5e4-cd6d-415f-a308-7cadd3f3aba8
---
=> Feat : page block focus issue 및 빈 블록 생성 구현

src/app/(main)/note/[id]/_components/note-content/block-button.tsx, src/app/(main)/note/[id]/_components/note-content/block/block.tsx, src/app/(main)/note/[id]/_components/note-content/block/handler/handleMouseLeave.ts, src/app/(main)/note/[id]/_components/note-content/block/handler/handleMouseMove.ts, src/app/(main)/note/[id]/_components/note-content/block/handler/handleMouseUp.ts, src/app/(main)/note/[id]/_components/note-content/note-content.tsx, src/app/(main)/note/[id]/_components/note-content/selection-menu/changeSelectionStyle.ts, src/app/(main)/note/[id]/_components/note-content/selection-menu/editSelectionContent.ts, src/app/(main)/note/[id]/_components/note-content/slash-menu/slash-menu.tsx
- 페이지 블록 이슈 해결
---
- 페이지 블록 전환 막기
- 페이지 블록 셀렉션 색 없애기
- 페이지 블록을 포함한 셀렉션 로직 점검
- selection에 페이지 블록이 껴있을때 속성 바꾸면 페이지블록 아닌 것에만 적용 되도록 변경
---
---
https://github.com/user-attachments/assets/b39d356d-1f6b-4513-947d-17a3ebc40052
---
---
=> feat : 페이지 블록 이슈 해결

src/app/(main)/_components/sidebar/finder/edit-title-modal.tsx, src/app/(main)/note/[id]/_components/note-content/selection-menu/selection-menu.tsx, src/app/(main)/note/[id]/_components/note-content/slash-menu/slash-menu.tsx, src/app/(main)/note/[id]/_components/note-header/cover-dropdown/dropdown.tsx, src/app/(main)/note/[id]/_components/note-header/note-header.tsx, src/app/(main)/note/[id]/_components/note-header/tag.tsx, src/app/auth/callback/[provider]/page.tsx, src/app/login/page.tsx, src/components/dropdown/dropdown-item.tsx, src/components/dropdown/dropdown-menu.tsx, src/components/dropdown/dropdown.tsx, src/hooks/useClickOutside.ts
- auth,login 및 기타 컴포넌트 리펙토링
---
- css 순서 변경 및 변수 이름 변경
- 미사용 로직 삭제
---
---
=> Refactor : auth,login 및 기타 컴포넌트 리펙토링

src/apis/client/block.ts, src/app/(main)/note/[id]/_components/note-content/block-button.tsx, src/app/(main)/note/[id]/_components/note-content/block/block-html-tag.tsx, src/app/(main)/note/[id]/_components/note-content/block/block.tsx, src/app/(main)/note/[id]/_components/note-content/ghost-block/ghost-block-html-tag.tsx, src/app/(main)/note/[id]/_components/note-content/ghost-block/ghost-block.tsx, src/app/(main)/note/[id]/_components/note-content/note-content.tsx, src/app/(main)/note/[id]/_components/note-content/slash-menu/slash-menu.tsx
- GhostBlock에 PAGE 타입 추가
---
- GhostBlock 컴포넌트에 block의 type이 PAGE 일 경우 추가
- GhostBlockHTMLTag 컴포넌트에 block의 type이 PAGE 일 경우 추가
---
---
**설명**: 이 PR과 관련된 추가적인 정보를 작성하여 리뷰어가 작업의 맥락을 이해하고, 리뷰에 필요한 내용을 쉽게 참고할 수
있도록 합니다. 이를 통해 PR의 내용을 명확히 전달할 수 있습니다.
---
https://github.com/user-attachments/assets/21a6d596-d022-4d72-ae30-596214fc2756
---
---
=> feat: GhostBlock에 PAGE 타입 추가

src/app/(main)/note/[id]/_components/note-content/block/block.tsx, src/app/(main)/note/[id]/_components/note-content/block/handler/handleMouseDown.ts, src/app/(main)/note/[id]/_components/note-content/block/handler/handleMouseLeave.ts, src/app/(main)/note/[id]/_components/note-content/block/handler/handleMouseMove.ts, src/app/(main)/note/[id]/_components/note-content/note-content.tsx
- 빠르게 selection을 설정하면 배경색이 비정상적이던 이슈 해결
---
- mouseLeave와 mouseMove 등 여러 곳에서 배경색을 칠해주는 로직들을 document로 옮겨 mouseMove 마다 배경색을 새로 칠해주어 비정상적으로 작동되던 이슈들을 해결했습니다.
- 또한 이로인해 span에서 mouseLeave가 되지 않던 이슈들도 해결되었습니다.
---
https://github.com/user-attachments/assets/a2905126-5008-4309-abda-8dae51535fdf
---
=> Fix : 빠르게 selection을 설정하면 배경색이 비정상적이던 이슈 해결

src/app/(main)/note/[id]/_components/note-content/block/block.tsx, src/app/(main)/note/[id]/_components/note-content/note-content.tsx, src/utils/fillHTMLElementBackgroundImage.ts
- 여러 줄 셀렉션 처리
---
- 여러 줄 셀렉션 처리를 위해 가상 셀렉션 배경색을 칠해주는 로직을 수정했습니다.
- 배경색을 칠할때 배경색을 칠할 left, right 좌표가 아니라 배경색을 칠할 시작 node와 시작 offset, 끝 node와 끝 offset을 이용하도록 로직을 수정했습니다.
---
---
https://github.com/user-attachments/assets/b38f103d-2880-4d69-a99b-d49f6eee0272
---
---
=> feat: 여러 줄 셀렉션 처리

src/app/(main)/_components/sidebar/finder/edit-title-modal.tsx, src/app/(main)/_components/sidebar/finder/note-item.tsx, src/app/(main)/error.tsx, src/app/(main)/layout.tsx, src/app/(main)/note/[id]/_components/note-content/block-button.tsx, src/app/(main)/note/[id]/_components/note-content/block/block.tsx, src/app/(main)/note/[id]/_components/note-content/block/handler/handleInput.ts, src/app/(main)/note/[id]/_components/note-content/block/handler/handleKeyDown.ts, src/app/(main)/note/[id]/_components/note-content/block/handler/handleMouseDown.ts, src/app/(main)/note/[id]/_components/note-content/block/handler/handleMouseMove.ts, src/app/(main)/note/[id]/_components/note-content/note-content.tsx, src/app/(main)/note/[id]/_components/note-content/selection-menu/changeSelectionStyle.ts, src/app/(main)/note/[id]/_components/note-content/selection-menu/editSelectionContent.ts, src/app/(main)/note/[id]/_components/note-content/slash-menu/slash-menu.tsx, src/app/(main)/note/[id]/_components/note-header/note-header.tsx, src/app/(main)/note/[id]/_components/note-header/tag.tsx, src/app/(main)/note/[id]/_components/note-header/title.tsx, src/app/(main)/note/[id]/page.tsx, src/app/auth/callback/[provider]/page.tsx, src/constants/toast-message.ts
- 에러 메세지 띄우기
---
- 서버 컴포넌트의 get 요청은 error.tsx 페이지를 통해 에러를 사용자에게 보여줍니다.
- post, put, delete 등의 요청은 toast를 이용해 사용자에게 보여줍니다.
---
---
=> feat: 에러 메세지 띄우기
